//
//  ControllerViewController.swift
//  controller
//
//  Created by Rosalind Ellis on 9/12/15.
//  Copyright (c) 2015 Rosalind Ellis. All rights reserved.
//

import UIKit
import WebKit

class ControllerViewController: UIViewController {
    
    var webView: WKWebView!  = WKWebView()
    

    override func viewDidLoad() {
        super.viewDidLoad()
        
        webView = WKWebView(frame: CGRectZero)
        
        // sets constraints of webview
        webView.setTranslatesAutoresizingMaskIntoConstraints(false) //disables autogenerated layout
        
        let width = NSLayoutConstraint(item: webView, attribute: .Width, relatedBy: .Equal, toItem: view, attribute: .Width, multiplier: 1, constant: 0) // define width equal to superview
        let top = NSLayoutConstraint(item: webView, attribute: .Top, relatedBy: .Equal, toItem: view, attribute: .Top, multiplier: 1, constant: 0)
        let bottom = NSLayoutConstraint(item: webView, attribute: .Bottom, relatedBy: .Equal, toItem: view, attribute: .Bottom, multiplier: 1, constant: 0)

        view.addConstraints([width, top, bottom])
        
        //load controller url
        let url = "CONTROLLERURL"
        let loadURL = NSURL(string: url)
        let requestObj = NSURLRequest(URL: loadURL!)
        webView.loadRequest(requestObj)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
